name: Every 4 Hours (Local Indexer, Permissions, All Donations & All Matching)

on:
  schedule:
    # Runs every four hours
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_Port }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      INDEXER_DB_HOST: ${{ secrets.INDEXER_DB_HOST }}
      INDEXER_DB_PORT: ${{ secrets.INDEXER_DB_PORT }}
      INDEXER_DB_NAME: ${{ secrets.INDEXER_DB_NAME }}
      INDEXER_DB_USER: ${{ secrets.INDEXER_DB_USER }}
      INDEXER_DB_PASSWORD: ${{ secrets.INDEXER_DB_PASSWORD }}
      DB_FDW_USERS: ${{ secrets.DB_FDW_USERS }}
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update Local Indexer Tables
      run: python automations/update_local_indexer_tables.py
      timeout-minutes: 55
    - name: Update All Donations & All Matching
      run: python automations/update_all_donations_and_matching_matviews.py
      timeout-minutes: 55
    - name: Refresh Dune Table
      run: python automations/refresh_dune_table.py
      timeout-minutes: 55
    - name: Update Allo Leaderboard
      run: python automations/refresh_allo_leaderboard.py
      timeout-minutes: 55
    - name: Upload Passport Model Scores
      run: python automations/upload_passport_model_scores.py
      timeout-minutes: 55
    - name: Update Permissions
      run: python automations/create_foreign_data_users.py
      timeout-minutes: 55


