name: Refresh Allo Leaderboard

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_FDW_USERS: ${{ secrets.DB_FDW_USERS }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update Allo Leaderboard
      run: python automations/refresh_allo_leaderboard.py
      timeout-minutes: 55
    - name: Update Permissions
      run: python automations/create_foreign_data_users.py
      timeout-minutes: 55
