name: Update Local Indexer Tables

on:
  schedule:
    # Runs every four hours
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_Port }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      INDEXER_DB_HOST: ${{ secrets.INDEXER_DB_HOST }}
      INDEXER_DB_PORT: ${{ secrets.INDEXER_DB_PORT }}
      INDEXER_DB_NAME: ${{ secrets.INDEXER_DB_NAME }}
      INDEXER_DB_USER: ${{ secrets.INDEXER_DB_USER }}
      INDEXER_DB_PASSWORD: ${{ secrets.INDEXER_DB_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python script
      run: python automations/update_local_indexer_tables.py
      timeout-minutes: 30


