name: Update All Donations & All Matching Materialized Views

on:
  schedule:
    # Runs at 5:00 UTC every day
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_Port }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python script
      run: python automations/update_all_donations_and_matching_matviews.py
      timeout-minutes: 55


